// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7__VRPDX1txr21ed7Wp9RWRY3Es--I0',
    appId: '1:1051456863553:web:29de50733d87885773f5c0',
    messagingSenderId: '1051456863553',
    projectId: 'reservations-8c32c',
    authDomain: 'reservations-8c32c.firebaseapp.com',
    storageBucket: 'reservations-8c32c.firebasestorage.app',
    measurementId: 'G-THNMJESY9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ZXN8cYepE-stRPGA2RifgDpxJE7mIe0',
    appId: '1:1051456863553:android:a735260fa9ec0b2e73f5c0',
    messagingSenderId: '1051456863553',
    projectId: 'reservations-8c32c',
    storageBucket: 'reservations-8c32c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgod854d-uvpJYQwsfIU8Pki2gAREitM',
    appId: '1:1051456863553:ios:26d0b7ae2c79231473f5c0',
    messagingSenderId: '1051456863553',
    projectId: 'reservations-8c32c',
    storageBucket: 'reservations-8c32c.firebasestorage.app',
    iosBundleId: 'com.example.reservationsSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHgod854d-uvpJYQwsfIU8Pki2gAREitM',
    appId: '1:1051456863553:ios:26d0b7ae2c79231473f5c0',
    messagingSenderId: '1051456863553',
    projectId: 'reservations-8c32c',
    storageBucket: 'reservations-8c32c.firebasestorage.app',
    iosBundleId: 'com.example.reservationsSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI7__VRPDX1txr21ed7Wp9RWRY3Es--I0',
    appId: '1:1051456863553:web:8739113feeefc06b73f5c0',
    messagingSenderId: '1051456863553',
    projectId: 'reservations-8c32c',
    authDomain: 'reservations-8c32c.firebaseapp.com',
    storageBucket: 'reservations-8c32c.firebasestorage.app',
    measurementId: 'G-060JHFGD0N',
  );
}
